title: Frenk Dragar
description: AI Engineer & Tech Writer | Bringing AI into EdTech
url: https://frenkd.github.io
author: Frenk Dragar
github_username: frenkd
linkedin_username: frenk-dragar

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  episodes:
    output: true
    permalink: /episodes/:title/
  appearances:
    output: true
    permalink: /appearances/:title/
  publications:
    output: true
    permalink: /publications/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Collection defaults
defaults:
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: episode
  - scope:
      path: ""
      type: "appearances"
    values:
      layout: appearance
  - scope:
      path: ""
      type: "publications"
    values:
      layout: default
  - scope:
      path: ""
      type: "projects"
    values:
      layout: default

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md

# Substack settings
substack_url: "https://dragarfrenk.substack.com"